### ISSUE TITLE
window创建项目

### ISSUE THREAD

**Issue by linyu520** [swordjs/sword-framework#11]
操作系统：window
node版本：17.1.0
sword-framework-cli版本：1.5.5-alpha.1
项目版本：1.2.14
运行npm run dev后成功开启3000端口

> 问题1：浏览器打开http://localhost:3000/api/hello后，报错

`{
  "statusCode": 404,
  "statusMessage": "Cannot find any route matching /api/hello.",
  "stack": []
}`
视频地址：https://7463-tcb-gfluxqbo6192a5-9dejpc39f97ec-1303861677.tcb.qcloud.la/20220808_093040.mp4
> 问题2：sword.config.ts文件报

`找不到模块“@swordjs/sword-framework-cli”或其相应的类型声明。`

> 问题3：sword.config.ts文件配置link属性

`const config: Config = {
  unicloud: {
    link: "E:/linyu/项目/昕晖建材/uniCloud-tcb/cloudfunctions/sword"
  }
};`
运行npm run dev:unicloud后报错
`Syntax error "n".sword/shim/unicloud.js:3:78:
      3 │   process.env._unicloud_shim_symlink_source_path = 'E:\sword\ghgh\.sword\dev\unicloud';`
视频地址：https://7463-tcb-gfluxqbo6192a5-9dejpc39f97ec-1303861677.tcb.qcloud.la/20220808_093404.mp4

**Comment by 1018715564** [comment]
收到, 我晚上看看

**Comment by 1018715564** [comment]
可能是在windows上没有经过测试, 有一些兼容性的问题, 我在mac上都没有复现
第二个问题你在本地装一下cli就行了, 装到dev里面, 我也发布了example最新的demo, 你可以直接下载看;
第三个同样没有复现, 应该是os兼容问题
等明天或者今天我用windows电脑跑一下, 我身边都是mac, 不好意思哈

**Comment by 1018715564** [comment]
最新的demo版本是1.2.15

**Comment by 1018715564** [comment]
我买一台windows服务器专门测试吧, 感谢兄弟, 我尽快给你解决

**Comment by 1018715564** [comment]
你可以先用mac跑, windows有蛮多兼容性问题的

**Comment by linyu520** [comment]
> 

好的，先用mac试试

**Comment by adun1982** [comment]
sword-framework
index.cjs
getApiMap中
 const mapValue = {
            sourcePath,
            method: [...value.methods],
            type: value.type,
            proto: (_a2 = apiJson[_key].proto) != null ? _a2 : null,
            handler
          };

 新增 _key= _key.replace('\\','/') 修改一下apiPath就能解决，

**Comment by 1018715564** [comment]
cli也有一些额外的东西需要适配, 这段时间实在很忙, 我会尽快发布最新的版本

**Comment by adun1982** [comment]
> cli也有一些额外的东西需要适配, 这段时间实在很忙, 我会尽快发布最新的版本

太好了。unicloud这玩意不支持ts，一直想搞无从下手。

**Comment by 1018715564** [comment]
> > cli也有一些额外的东西需要适配, 这段时间实在很忙, 我会尽快发布最新的版本
> 
> 太好了。unicloud这玩意不支持ts，一直想搞无从下手。

嗯嗯好的

**Comment by 1018715564** [comment]
最新版本已经修复, 各位不好意思, 我后续将会继续维护, 不过重心会转到编译方向, 其他平台兼容得看时间

**Comment by 1018715564** [comment]
https://github.com/swordjs/sword-framework/releases/tag/v1.4.1

**Comment by 1018715564** [comment]
更新cli和runtime到最新版本即可
