### ISSUE TITLE
mac系统项目问题

### ISSUE THREAD

**Issue by linyu520** [swordjs/sword-framework#12]
操作系统：mac
node版本：16.16.0
cli版本：1.5.5-alpha.3
项目版本：1.2.15

> 问题一：cli无法监听使用_add快捷创建

> 问题二：软连接到uniapp后，无法运行本地函数，报错运行参数错误

视频地址：[(https://7463-tcb-gfluxqbo6192a5-9dejpc39f97ec-1303861677.tcb.qcloud.la/屏幕录制2022-08-11 上午10.05.49.mov)](url)

**Comment by linyu520** [comment]
问题二原因已知，作废！
改成

> 问题三：运行本地函数后，报错
`Cannot find module @swordjs/sword-frameword`

**Comment by linyu520** [comment]
需要在uniapp项目里npm i 吗

**Comment by linyu520** [comment]
uniapp项目npm install后，重新运行本地函数，报错
`require(...).main is not a function`

**Comment by 1018715564** [comment]
不需要install, 这段时间真的很忙, 我可能得下周周内才能解决

**Comment by linyu520** [comment]
好的，不用install就好，不然光npm包就2MB了！

**Comment by 1018715564** [comment]
1. 操作符要在dev环境下使用, 你直接没有dev环境, 我这里这么监听的到你的文件夹改变了呢?
2. uniapp这部分已经修复了
请更换最新版本的cli和runtime, 并且重新上传云函数
ps: build出来的云函数是生产环境, 你仅需要“上传并且运行即可”, 是不能在本地调试的, 如果在本地调试生产环境的代码, 就要安装node依赖
