### ISSUE TITLE
Mac 运行错误

### ISSUE THREAD

**Issue by linyu520** [swordjs/sword-framework#13]
node版本：v16.16.0
sword-framework-cli版本：1.5.5-alpha.4
Hbuilder X版本：3.5.3

> 问题：cli创建项目并且pnpm i后，按文档运行dev:unicloud报错
`no such file or directory, open '/Applications/HBuilderX.app/Contents/HBuilderX/plugins/unicloud/manager/src/api.json'`
已经在sword.config.ts配置过link，并且uniappa项目里index.js配置好exports.main = require("./sword/src/index.js");

**Comment by 1018715564** [comment]
这个问题我还遇到过, 我回去复现一下

**Comment by 1018715564** [comment]
升级一下framework程序1.4.1-alpha.1试一下

**Comment by linyu520** [comment]
dev环境下快捷使用_add创建API，报错
`no such file or directory, open '/Users/toybaba/Desktop/多商户管理系统admin/src/api/_add/proto.ts'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/toybaba/Desktop/多商户管理系统admin/src/api/_add/proto.ts'
}`

**Comment by linyu520** [comment]
npm run build:unicloud打包后，在HbuilderX里运行本地云函数报错
`Cannot find module '@swordjs/sword-framework'`

**Comment by 1018715564** [comment]
首先你要知道unicloud的原理, 既然是prod生产, 你就应该上传云函数, 而不是本地执行, 如果你要本地执行就得npm install;
云函数在云上也是要安装依赖的, 所以你试试上传并且运行云函数

**Comment by 1018715564** [comment]
> dev环境下快捷使用_add创建API，报错 `no such file or directory, open '/Users/toybaba/Desktop/多商户管理系统admin/src/api/_add/proto.ts'] { errno: -2, code: 'ENOENT', syscall: 'open', path: '/Users/toybaba/Desktop/多商户管理系统admin/src/api/_add/proto.ts' }`

我这里应该没有复现, 我晚上回去试试, 是mac么, 我之前测试过, 是可以的

**Comment by linyu520** [comment]
还是一样Mac

**Comment by 1018715564** [comment]
我在公司没办法试, 我回家看看, 你可以提pr么

**Comment by 1018715564** [comment]
我windows support还没做完, windows我远程调试太痛苦了
